(custom-set-variables
 '(user-login-name "tgkirk" t)
 '(load-home-init-file t t)
 '(toolbar-news-use-separate-frame nil)
 '(archive-zip-extract (quote ("unzip")))
 '(display-time-echo-area nil)
 '(tab-width 4)
 '(fill-column 200)
 '(visible-bell t)
 '(toolbar-news-reader (quote gnus))
 '(toolbar-mail-reader (quote vm))
 '(dired-listing-switches "-alt")
 '(archive-zip-use-pkzip nil)
 '(bell-volume 20)
 '(display-time-day-and-date t)
 '(user-mail-address "tony.kirke@dolby.com")
 '(list-directory-verbose-switches "-lat")
 '(query-user-mail-address nil)
 '(gnus-package t))
 '(highline-face (quote highline-face))
 '(toolbar-visible-p t)
 '(toolbar-mail-reader (quote vm))
 '(hexl-follow-ascii nil)
 '(template-subdirectories (quote ("./" "templates/")))
(custom-set-faces
 '(default ((t (:foreground "dark blue" :background "lightblue1" :size "18pt" :family "Courier"))) t)
 '(font-lock-string-face ((((class color)) (:foreground "green4"))))
 '(nil nil)
 '(region ((((class color)) (:background "wheat"))))
 '(dired-face-setuid ((((class color)) (:bold t :foreground "Green"))))
 '(font-lock-variable-name-face ((((class color)) (:foreground "brown"))))
 '(highline-face ((t (:foreground "black" :background "yellow"))))
 '(font-lock-keyword-face ((((class color)) (:foreground "orange"))))
 '(font-lock-type-face ((((class color)) (:foreground "blue"))))
; '(font-lock-comment-face ((((class color)) (:foreground "green4" :background "white" :size "14" :family "arial" :italic t))))
 '(dired-face-executable ((((class color)) (:bold t :foreground "SeaGreen"))))
 '(font-lock-function-name-face ((((class color)) (:foreground "firebrick"))))
 '(highlight ((((class color)) (:background "green1"))) t)
 '(dired-face-symlink ((((class color)) (:foreground "brown"))))
 '(buffers-tab ((t (:foreground "black" :background "Gray80" :size "13"))) t))

